### ISSUE TITLE
Inquiry Regarding Training Material in the Repository

### ISSUE THREAD

**Issue by crux82** [hamiltonoh/OrganAge#2]
Dear @hamiltonoh 

First of all, thank you for your work and congratulations on the work published in Nature.

I am currently exploring the repository associated with your work but have encountered some difficulty in locating the specific materials used for training the model. While I noticed that the repository includes data pertaining to 200 individuals in the ``test`` folder, the training dataset seems to be absent or not immediately identifiable.

Could you kindly assist me in locating the training material within the repository? 

Thank you in advance for your time and assistance!

Bests 

Danilo

**Comment by hamiltonoh** [comment]
Thanks Danilo!

Unfortunately, the data is not publicly accessible due to patient privacy and data ownership reasons. Our training data were samples from the healthy controls in the Knight-ADRC cohort, which can be provided upon reasonable requested here https://www.niagads.org/knight-adrc-collection. Hope this helps.

Best,
Hamilton

**Comment by crux82** [comment]
Dear Hamilton

thank you very much for your quick reply. 

Bests

Danilo
