### ISSUE TITLE
Portablity to Olink protein data

### ISSUE THREAD

**Issue by VasiliosRaptis** [hamiltonoh/OrganAge#4]
Dear all,

Thank you for this very interesting work.

In your manuscript it is mentioned that your approach is platform agnostic. I was wondering whether your model's code can be adapted to run on plasma proteins measured on a different platform instead of Somascan, e.g. olink. 

Best wishes
Vasilis

**Comment by hamiltonoh** [comment]
Hi Vasilis,

The models in the manuscript can only be applied to SomaScan data, since they were trained on SomaScan data, and Olink vs Soma correlations are moderate.

Aging models broadly can be trained on any platform (ie. Olink, Soma, methylation) with standard Elastic Net or Lasso regression. I suggest using the "LassoCV" function from sklearn package in python, if interested. We are also working on organ aging models in Olink, which will hopefully be made available on biorxiv and github in the next few months.

Best,
Hamilton

**Comment by VasiliosRaptis** [comment]
Dear Hamilton,

Thank you very much for your answer!

Vasilis

**Comment by yaolin101** [comment]
Hi Hamilton,

really nice work!
wondering if the organ aging models in Olink are now available?

Thanks,
Yao

**Comment by hamiltonoh** [comment]
Yes, in the supplementary tables here https://www.biorxiv.org/content/10.1101/2024.06.07.597771v1

**Comment by yaolin101** [comment]
how about untargeted MS proteomics data?

**Comment by hamiltonoh** [comment]
We are not working on untargeted MS proteomics.
